name: keu_app
description: Aplikasi pencatatan keuangan pribadi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Charts dan Grafik
  fl_chart: ^0.66.0
  
  # Tipografi Custom
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Date Formatting
  intl: ^0.19.0

  # Routing
  go_router: ^14.1.0

  # Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/